name: avaliacao07
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependências adicionais podem ser adicionadas aqui, se necessário

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true