name: avaliacao_04
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.7.3

# Add regular dependencies here.
dependencies:
  sqflite_common_ffi: ^2.0.0
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
